// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGoMe-M466jfcSCBoNE6MAZ5-NSvFV7U',
    appId: '1:496857956954:web:f4e71d203064ab0ae68e63',
    messagingSenderId: '496857956954',
    projectId: 'una-vida-brillante',
    authDomain: 'una-vida-brillante.firebaseapp.com',
    storageBucket: 'una-vida-brillante.appspot.com',
    measurementId: 'G-B3P628WYLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuWeqH-r2HySwdXfrYARRsEksf52GTMs',
    appId: '1:496857956954:android:aef490560d671101e68e63',
    messagingSenderId: '496857956954',
    projectId: 'una-vida-brillante',
    storageBucket: 'una-vida-brillante.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBByWEhsxiqT1PuvNs_ECri482y_YDiVbY',
    appId: '1:496857956954:ios:ed47cc9ee8c979aee68e63',
    messagingSenderId: '496857956954',
    projectId: 'una-vida-brillante',
    storageBucket: 'una-vida-brillante.appspot.com',
    iosClientId: '496857956954-u03joc21cuhvliu5ni2je5d2r3dgd0na.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationUnavidabrillante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBByWEhsxiqT1PuvNs_ECri482y_YDiVbY',
    appId: '1:496857956954:ios:ed47cc9ee8c979aee68e63',
    messagingSenderId: '496857956954',
    projectId: 'una-vida-brillante',
    storageBucket: 'una-vida-brillante.appspot.com',
    iosClientId: '496857956954-u03joc21cuhvliu5ni2je5d2r3dgd0na.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationUnavidabrillante',
  );
}
